import React from 'react'

function About() {
    return (
        <div className='Home-section'>
            <h1>About</h1>
            <p>
            The main objective was to give a framework where ECP can conduct elections online. In Pakistan, The voting for general elections is physically a colossal amount of poll paper was print, for voting everyone must come within the polling station, stand within the line and wait for their turn. Government workers were select and paid for votes tallying. The complete election gets expensive to the government. 
This system is developed to vary the manual elections system with proficient and successful online election system. This system will supportive for both the government and therefore the voters.
There is no got to print poll paper and government representatives for tallying of votes. Voters can cast their votes from any remote area in Pakistan with access the Internet. Some of main objectives are.<br/>
•	In this system the user can login with its unique ID card no which is generated by NADRA and the password is sent via SMS through which he can login. <br/>
•	If the person cast their vote he/ she will not be able to cast their vote again.<br/>
•	The system will automatically count vote for different party. The parties which get highest vote win the election.<br/>
•	The time period for vote casting is set by Election commission. <br/>
•	Making the system secure with high encryption standards so no one can hack into or manipulate with the data.

            </p>

        </div>
    )
}

export default About
